blueprint:
  name: "Bidirectional Sync for Two To-Do Lists"
  description: "Synchronizes two Home Assistant to-do lists, ensuring both contain the same items."
  domain: automation
  input:
    list_1:
      name: List 1
      description: "Select your first list to synchronize."
      selector:
        entity:
          domain: todo
          multiple: false
    list_2:
      name: List 2
      description: "Select your second list to synchronize."
      selector:
        entity:
          domain: todo
          multiple: false

tigger:
  - platform: state
    entity_id:
      - !input 'list_1'
  - platform: state
    entity_id:
      - !input 'list_2'

action:
  - variables:
      list_1: !input 'list_1'
      list_2: !input 'list_2'
  
  - service: todo.get_items
    target:
      entity_id: "{{ list_1 }}"
    data:
      status: needs_action
    response_variable: list_1_items

  - service: todo.get_items
    target:
      entity_id: "{{ list_2 }}"
    data:
      status: needs_action
    response_variable: list_2_items

  - variables:
      items_1: "{{ list_1_items[list_1]['items'] | map(attribute='summary') | list }}"
      items_2: "{{ list_2_items[list_2]['items'] | map(attribute='summary') | list }}"
      items_to_add_1: "{{ items_2 | difference(items_1) }}"
      items_to_add_2: "{{ items_1 | difference(items_2) }}"

  - repeat:
      for_each: "{{ items_to_add_1 }}"
      sequence:
        - service: todo.add_item
          target:
            entity_id: "{{ list_1 }}"
          data:
            item: "{{ repeat.item }}"

  - repeat:
      for_each: "{{ items_to_add_2 }}"
      sequence:
        - service: todo.add_item
          target:
            entity_id: "{{ list_2 }}"
          data:
            item: "{{ repeat.item }}"
