blueprint:
  name: Bidirectional List Sync
  description: Synchronizes two lists bi-directionally.  Changes in either list will be reflected in the other.
  domain: automation

  input:
    list_1_entity:
      name: List 1 Entity
      description: The entity ID of the first list.
      selector:
        entity:
          filter:
            domain: input_list
    list_2_entity:
      name: List 2 Entity
      description: The entity ID of the second list.
      selector:
        entity:
          filter:
            domain: input_list

  variables:
    list_1_entity: !input list_1_entity
    list_2_entity: !input list_2_entity

trigger:
  - platform: state
    entity_id: !input list_1_entity
  - platform: state
    entity_id: !input list_2_entity

action:
  - choose:
      - conditions: "{{ trigger.entity_id == list_1_entity }}"
        sequence:
          - service: input_list.set_list
            data:
              entity_id: "{{ list_2_entity }}"
              items: "{{ state_attr(list_1_entity, 'items') | default([]) }}"
      - conditions: "{{ trigger.entity_id == list_2_entity }}"
        sequence:
          - service: input_list.set_list
            data:
              entity_id: "{{ list_1_entity }}"
              items: "{{ state_attr(list_2_entity, 'items') | default([]) }}"
    default: [] # Should never happen, but good practice

mode: restart # Important: Restart automation if HA restarts to ensure sync continues