blueprint:
  name: "Synchronize 2 Home Assistant todo list"
  description: |
    This blueprint synchronizes 2 to-do lists. Originally designed to sync 
    Google Keep lists with the Bring shopping list, its versatility allows 
    syncing any list. Currently limited to syncing only active items, 
    those marked as completed are removed from the lists.
  source_url: https://gist.github.com/hectorzin/53f9811ff2d6a673af9ff3a9801df7af
  domain: automation
  input:
    google_list:
      name: List 1
      description: Select your first list to synchronize
      selector:
        entity:
          domain:
            - todo
          multiple: false
    bring_list:
      name: List 2
      description: Select your second list to synchronize
      selector:
        entity:
          domain:
            - todo
          multiple: false
    temp_list:
      name: Temp List
      description: Select the temporary list that is used as the basis of the synchronization
      selector:
        entity:
          domain:
            - todo
          multiple: false

trigger:  # Corrected typo here!
  - platform: state
    entity_id:
      - !input google_list
  - platform: state
    entity_id:
      - !input bring_list

action:
  - choose:
      - conditions: "{{ trigger.entity_id == list_1_entity }}"
        sequence:
          - service: input_list.set_list
            data:
              entity_id: "{{ list_2_entity }}"
              items: "{{ state_attr(list_1_entity, 'items') | default([]) }}"
      - conditions: "{{ trigger.entity_id == list_2_entity }}"
        sequence:
          - service: input_list.set_list
            data:
              entity_id: "{{ list_1_entity }}"
              items: "{{ state_attr(list_2_entity, 'items') | default([]) }}"
    default: [] # Should never happen, but good practice

mode: restart # Important: Restart automation if HA restarts to ensure sync continues